#!/usr/bin/env python

"""
*********************************************************************
* Software License Agreement (BSD License)
*
*  Copyright (c) 2020, PickNik Inc.
*  All rights reserved.
*
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*   * Redistributions of source code must retain the above copyright
*     notice, this list of conditions and the following disclaimer.
*   * Redistributions in binary form must reproduce the above
*     copyright notice, this list of conditions and the following
*     disclaimer in the documentation and/or other materials provided
*     with the distribution.
*   * Neither the name of PickNik Inc nor the names of its
*     contributors may be used to endorse or promote products derived
*     from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
*  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
*  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
*  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
*  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
*  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
*  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
*  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
*  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
*  POSSIBILITY OF SUCH DAMAGE.
*********************************************************************
 Author: Boston Cleek
 Desc:   The server calls a script running the GQCNN

 PARAMETERS:
    dexnet_policy_script - executable python3 script of the dexnet policy
 SERVICES:
    gqcnn_grasp (GQCNNGrasp) - service requests the grasp candidate from
                               the learned policy and the probability of success
"""


# Python
import subprocess
import numpy as np

# ROS
import rospy
import pickle
from geometry_msgs.msg import PoseStamped
from moveit_task_constructor_dexnet.srv import GQCNNGrasp, GQCNNGraspResponse

# TODO: load from param server
grasp_file = "/home/bostoncleek/GPD_ws/src/deep_grasp_demo/moveit_task_constructor_dexnet/data/grasps/grasp_candidates.bin"



class GraspServer():
    """ Advertise a grasp candidate service """

    def __init__(self):
        """ Constructor """

        self.policy_script = rospy.get_param('~dexnet_policy_script')
        self.grasp_serv = rospy.Service('gqcnn_grasp', GQCNNGrasp, self.handle_grasp)


    def handle_grasp(self, req):
        """  Callback for GQCNNGrasp sevice

        Creates a subprocess (python3 script running the GQCNN) to compose the
        grasp candidate and q_value

        Args:
            req (GQCNNGrasp): input is a string for the name of the request

        Return:
            GQCNNGraspResponse (geometry_msgs/PoseStamped and float64): the 6DOF
                grasp pose and the score representing the probability of success
        """

        rospy.loginfo("GQCNN service activated")

        ######################################################################
        # start subprocess
        proc = subprocess.Popen(['python3', self.policy_script], stdin=subprocess.PIPE)


        # sends data to stdin, read data from stdout, waits until process reaches end of file
        # TODO: pass additional args to python3 script
        proc_out = proc.communicate(req.color_img_file_path + '\n' +
                                    req.depth_img_file_path + '\n')[0]
        # end subproces
        ######################################################################

        # sampled grasps
        sols_file = open(grasp_file, 'rb')
        data = pickle.load(sols_file)
        sols_file.close()

        # probability of success
        q_val = data[2]

        grasp_pose = PoseStamped()
        grasp_pose.header.frame_id = data[3]
        # position [x y z]
        grasp_pose.pose.position.x = data[0][0]
        grasp_pose.pose.position.y = data[0][1]
        grasp_pose.pose.position.z = data[0][2]

        # orientation [qw qx qy qz]
        grasp_pose.pose.orientation.w = data[1][0]
        grasp_pose.pose.orientation.x = data[1][1]
        grasp_pose.pose.orientation.y = data[1][2]
        grasp_pose.pose.orientation.z = data[1][3]

        return GQCNNGraspResponse(grasp_pose, q_val)


def main():
    rospy.init_node('gqcnn_server')
    grasp_server = GraspServer()
    rospy.spin()


if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass
